language: php

php:
  - 5.3
  - 5.4

before_script:
  - "composer install --verbose"

script: phpunit --verbose --coverage-text --configuration test/

after_script:
  - "phpunit --testdox --configuration test/"
